### ISSUE TITLE
Bitcoin SV make check report fail and bitcoind run in segmentation fault 11.

### ISSUE THREAD

**Issue by passionofvc** [bitcoin-sv/bitcoin-sv#42]
### Can you reliably reproduce the issue?
the bitcoind run in segv, when use berkeley-db@18
#### If so, please list the steps to reproduce below:
1. ./autogen.sh 
    ./configure --enable-debug

2. make
Making all in doc/man
make[1]: Nothing to be done for `all'.
make[1]: Nothing to be done for `all-am'.

3.make check

### Expected behaviour
test should ok

### Actual behaviour
FAIL: test/test_bitcoin

```
$ make check
Making check in src
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS check-local
FAIL: test/test_bitcoin
============================================================================
Testsuite summary for Bitcoin SV 0.1.0
============================================================================
 # TOTAL: 1
 # PASS:  0
 # SKIP:  0
 # XFAIL: 0
 # FAIL:  1
 # XPASS: 0
 # ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin-sv/bitcoin-sv/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

### What version of bitcoin-sv are you using?
master

### Machine specs:
- OS   : macOS Mojave 10.14.1
- CPU : 3.8GHz Intel core i5
- RAM:  8G
- Disk size: 
- Disk Type (HD/SDD): SDD 1TB
 ==========================================
    Bitcoin SV 0.1.0: src/test-suite.log
 ==========================================
 
 # TOTAL: 1
 # PASS:  0
 # SKIP:  0
 # XFAIL: 0
 # FAIL:  1
 # XPASS: 0
 # ERROR: 0
 
 .. contents:: :depth: 2
 
 FAIL: test/test_bitcoin
 =======================
 
 Running 302 test cases...
 unknown location:0: ^[[4;31;49mfatal error: in "accounting_tests/acc_orderupgrade": memory access violation at address: 0x00a00000: no mapping at fault         address^[[0;39;49m
 wallet/test/accounting_tests.cpp:28: ^[[1;36;49mlast checkpoint: "acc_orderupgrade" fixture ctor^[[0;39;49m
 
 ^[[1;31;49m*** 1 failure is detected in the test module "Bitcoin Test Suite"
 ^[[0;39;49mFAIL test/test_bitcoin (exit status: 201)
```

#run bitcoind 
```
$ ./bitcoind -regtest
Segmentation fault: 11

$ lldb ./bitcoind 
(lldb) target create "./bitcoind"
Current executable set to './bitcoind' (x86_64).
(lldb) run -regtest
Process 17995 launched: './bitcoind' (x86_64)
Process 17995 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x100000)
    frame #0: 0x0000000101bb760e libdb_cxx-18.1.dylib`__env_get_blob_threshold_int + 127
libdb_cxx-18.1.dylib`__env_get_blob_threshold_int:
->  0x101bb760e <+127>: movl   %eax, (%r14)
    0x101bb7611 <+130>: xorl   %r15d, %r15d
    0x101bb7614 <+133>: movl   %r15d, %eax
    0x101bb7617 <+136>: popq   %rbx
Target 0: (bitcoind) stopped.

$ otool -L bitcoind
bitcoind:
	/usr/local/opt/boost/lib/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_chrono-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/berkeley-db/lib/libdb_cxx-18.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/miniupnpc/lib/libminiupnpc.17.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/libevent/lib/libevent_pthreads-2.1.6.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/local/opt/libevent/lib/libevent-2.1.6.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

**Comment by Danconnolly** [comment]
Thanks, this was fixed.

**Comment by diadal** [comment]
@passionofvc  please how did you fix this issue am facing the same

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS check-local
FAIL: test/test_bitcoin
============================================================================
Testsuite summary for Bitcoin SV 1.0.1
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/bitcoin-sv/bitcoin-sv/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

**Comment by passionofvc** [comment]
@diadal  sorry for late, I pull the master branch, build again, but the segv is not fixed.

```
$ ./bitcoind --help
dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /app/bitcoin-sv/build/./bitcoind
  Reason: image not found
Abort trap: 6

$ ldd bitcoind 
bitcoind:
	/usr/local/opt/boost/lib/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_program_options-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_chrono-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/berkeley-db/lib/libdb_cxx-18.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/miniupnpc/lib/libminiupnpc.17.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/libevent/lib/libevent_pthreads-2.1.6.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/local/opt/libevent/lib/libevent-2.1.6.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```
